"""unique stuid and realname

Revision ID: 1083bccb3278
Revises: b295b033364d
Create Date: 2019-11-02 02:40:12.350480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1083bccb3278'
down_revision = 'b295b033364d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['website'])
    op.create_unique_constraint(None, 'users', ['affiliation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
